apiVersion: v1
kind: Service
metadata:
  name: forumgw-service
  namespace: forumgw
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: forumgw
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forumgw
  namespace: forumgw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forumgw
  template:
    metadata:
      labels:
        app: forumgw
    spec:
      containers:
        - name: forumgw
          image: forumgw-v2:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: forumgw-secrets
