apiVersion: v1
kind: Secret
metadata:
  name: forumgw-secrets
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXM6Ly9wb3N0Z3Jlczpwb3N0Z3Jlc0Bwb3N0Z3Jlcy1zZXJ2aWNlOjU0MzIvZm9ydW1nd19zdmVsdGU=
  JWT_SECRET: WXlDeFl5cFlQaWpwWE5FUExVcWpvajJHNjQyQmpkMHR4Rnl5djU1NDg2bU5MOElwTVFLcDJjWUtzd3NtckV2MFAxcVk2VWNhTkR2R3ZNWnVFQjBJMVE9PQ==